version: "3.7"

services:

  pyx:
    image: emcniece/dockeryourxyzzy:latest
    build: ./
    ports:
     - "8080:8080"
    volumes:
      - ./overrides:/overrides
    networks:
      - pyx-net
    environment:
      - TOMCAT_USER=tomcat_user
      - TOMCAT_PASSWORD=tomcat_password
      - DB_NAME=pyx
      - DB_USER=pyx
      - DB_PASSWORD=CorrectHorseBatteryStaple

  postgres:
    image: "postgres:alpine"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
      - ./init-db.d:/docker-entrypoint-initdb.d
    networks:
      - pyx-net
    environment:
      - POSTGRES_DB=pyx
      - POSTGRES_USER=pyx
      - POSTGRES_PASSWORD=CorrectHorseBatteryStaple

  ngrok:
    image: wernight/ngrok:latest
    networks:
      - pyx-net
    ports:
      - "4040:4040"
    environment:
      - NGROK_PORT=pyx:8080

networks:
  pyx-net:
